### ISSUE TITLE
Finding Catmandu::Store::Elasticsearch on cpanmetadb failed.

### ISSUE THREAD

**Issue by jorol** [LibreCat/Catmandu-Store-Elasticsearch#5]
I get this error when installing the new version:

    $ cpanm Catmandu::Store::Elasticsearch
    ! Finding Catmandu::Store::Elasticsearch on cpanmetadb failed.

And it´s not available on metacpan <https://metacpan.org/search?q=Catmandu%3A%3AStore%3A%3AElasticsearch>

**Comment by phochste** [comment]
There is even for Elasticsearch (with small 's' an problem on cpan):

https://metacpan.org/pod/Elasticsearch

    Because of the name clash between ElasticSearch.pm and Elasticsearch.pm the official Perl client is now called: Search::Elasticsearch.
    See https://github.com/elasticsearch/elasticsearch-perl/issues/20 for details.
    This distribution will be removed from CPAN in 2015. Please update your code.

**Comment by nics** [comment]
jikes,

it's there alright
https://metacpan.org/pod/release/NICS/Catmandu-Store-Elasticsearch-0.03/lib/Catmandu/Store/Elasticsearch.pm

(parts) of the cpan infrastructure are case-insensitive? that seems like 
a strange choice since perl modules are.

we'd better rename the store then

Catmandu::Store::Es
Catmandu::Store::Search::Elasticsearch
?

**Comment by jorol** [comment]
The old ElasticSearch modules are scheluded by pause to be deleted and moved to backpan on friday morning.
